name: Dataform CI/CD Workflow

on:
  pull_request:
    branches:
      - main
    # Se activa cuando se crea un Pull Request hacia la rama main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Descargar el repositorio
      - name: Check out repo
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js para instalar Dataform CLI
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Paso 3: Instalar la CLI de Dataform
      - name: Install Dataform CLI
        run: npm install -g @dataform/cli

      # Paso 4: Crear el archivo .df-credentials.json
      - name: Create Dataform credentials file
        run: |
          echo "${{ secrets.GCLOUD_SERVICE_KEY }}" > .df-credentials.json

      # Paso 5: Autenticar con GCP (opcional si usas gcloud)
      - name: Authenticate with GCP
        run: |
          gcloud auth activate-service-account --key-file=.df-credentials.json
          gcloud config set project proj-nyc-taxi-pipeline

      # Paso 5: Ejecutar pipeline en staging
      - name: Run Dataform in Staging
        run: |
          ENVIRONMENT=staging dataform run

      # Paso 6: Ejecutar pipeline en producción
      - name: Run Dataform in Production
        if: success()
        run: |
          ENVIRONMENT=prod dataform run


